- name: Install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Setup Application  
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup


